// Generated by CoffeeScript 2.1.1
(function() {
  // This file is part of switch-reducers
  // Copyright (C) 2018-present Dario Giovannetti <dev@dariogiovannetti.net>
  // Licensed under MIT
  // https://github.com/kynikos/switch-reducers/blob/master/LICENSE
  module.exports = function(getControlVar, reducersMap) {
    return function(...args) {
      var reduce;
      reduce = reducersMap[getControlVar(...args)];
      if (reduce != null) {
        return reduce(...args);
      }
      return null;
    };
  };

}).call(this);
